### ISSUE TITLE
Released version does not match/follow master branch

### ISSUE THREAD

**Issue by cristiandouce** [Asana/node-asana#100]
I don't get why this: https://github.com/Asana/node-asana/blob/v0.12.0/lib/client.js
Is not the same as this: https://github.com/Asana/node-asana/tree/master/lib/client.js

specially after seeing this commit IN master 2 days ago: https://github.com/Asana/node-asana/commit/412450483b1a6819f6e88c42cd0075dbaf62714c

When I do npm install, I have a lot of missing features.

Also, you have a typo in the README.md saying `userAccessToken()` when it should say `useAccessToken()`

**Comment by slobak** [comment]
That is definitely strange, perhaps something broke in our deploy process. We'll take a look.

**Comment by cristiandouce** [comment]
@slobak Thanks! Let me know please when ready. Also npm package does not match FYI

**Comment by slobak** [comment]
@noonhub you deployed recently for the new user mgmt features, and it looks a couple of version bumps happened - did anything strange happen during the workflow?

**Comment by cristiandouce** [comment]
@slobak @noonhub any update on this?

Thanks!

**Comment by noonhub** [comment]
@slobak I cannot remember why I bumped it twice in a row, that does seem odd but I am also not sure why that would cause master to diverge. I will try looking into this some more and see what might be happening.

**Comment by noonhub** [comment]
@cristiandouce @slobak this should be sorted out now with `v0.12.1`. I am guessing that something failed with the last deploy. If this comes up again we will try to dig deeper and see what is going wrong in our deploy process.

**Comment by cristiandouce** [comment]
@noonhub awesome, thanks!
