### ISSUE TITLE
Keep getting - The `code` provided was invalid.

### ISSUE THREAD

**Issue by thinklinux** [Asana/node-asana#115]
I'm doing the `Authorization Code Grant`. Here is what I do:

Creating an Asana client

```js
var createClient = function () {
	return Asana.Client.create({
		clientId: clientId,
		clientSecret: clientSecret,
		redirectUri: redirectUri
	});
}
```

Take the url to redirect the user
```js
var client = createClient();
var url = client.app.asanaAuthorizeUrl();
```

Use the code to request access_token
```js
var client = createClient();

client.app.accessTokenFromCode(code)
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })
```

I keep getting this error
```
{
  "error": "invalid_grant",
  "error_uri": "https://asana.com/developers/documentation/getting-started/authentication",
  "error_description": "The `code` provided was invalid."
}

```

Am I missing something here or this should be the correct way of doing this?

**Comment by slobak** [comment]
Are you sure the code you're sending is the exact one you're getting back from the authorization? That is the most likely cause of this error. The code generally begins with `0/`. Note codes expire after a relatively short time (like 15 minutes).

**Comment by thinklinux** [comment]
I've made some screenshots for you with the code. The time interval is less then a second so I don't think expiration is the problem there.

![popup](https://cloud.githubusercontent.com/assets/326949/13423370/268798fe-dfa3-11e5-95ce-1e8c2e9207b1.png)

![nodejs](https://cloud.githubusercontent.com/assets/326949/13423289/a2d3a2d2-dfa2-11e5-9b3a-3362d905980f.png)

**Comment by agnoster** [comment]
As Greg said, the code begins with 0/ - it looks like you're either
double-escaping or when you extract http params it's not unescaping
(hence the %2F encoding the /)

**Comment by agnoster** [comment]
How are you getting the code from your HTTP stack? Normally it should be parsed correctly for you, url decoding is pretty much required to make sense of your query params.

**Comment by thinklinux** [comment]
@agnoster You were absolutely right. I didn't decode my query params. I have no idea how I missed that especially after Greg's response. Thanks a lot guys! Everything is working great now.

**Comment by arcl30** [comment]
Hi Guys!

Can you please show an example on how to configure a Authorization Code Grant? Would be very glad if you'll help me with this one. 

Thanks!

**Comment by thinklinux** [comment]
@arcl30 https://github.com/Asana/node-asana/tree/master/examples/oauth/webserver

**Comment by arcl30** [comment]
I am using the Pop-up flow and I've seen on the source code comments that all implementing class of BaseFlow can only use implicit grant. My question is, is there an authorization grant for Pop-up type?

Thanks for your help

**Comment by slobak** [comment]
Popup flows run in the browser, which means non-secure client code. You should not store or use secret keys from your client code (which is accessible to anyone), so that means you cannot use the server-side flows like the authorization grant. The implicit grant exists specifically for browser-side flows like the one you are using—we provide both a Popup and a Redirect version, but they both use the implicit grant under the hood.

**Comment by AlexRoy96** [comment]
thank you so much for this thread, was looking for a solution for forever
