### ISSUE TITLE
Update errors

### ISSUE THREAD

**Issue by joeinnes** [Asana/node-asana#122]
Long story short, I'm trying to write my own Asana/iDoneThis integration.

I've got as far as passing Asana's completed tasks to iDoneThis, and now I want to set a custom field to use to exclude these from future sweeps.

Here's my code, but it doesn't seem to be adding the 'external' data:

tasks is the array of tasks.
```
tasks.forEach(function (task) {
            var extStr = JSON.stringify({
                "id": task.id,
                "data": 'passedToIDT'
            });
            var data = {
              notes: task.notes ? task.notes + '\nDone...' : 'Done...',
              external: extStr
            }
            client.tasks.update(task.id, data)
            .then(function (resp) {
                console.log(resp);
            });
        });
```

I get 'Unhandled rejection Error: Server Error' when running the code as above.

I also tried `JSON.stringify(data)` as the second argument to the update method, but that just did nothing (there was no error, but the external data was not set).

**Comment by slobak** [comment]
Why are you stringifying the JSON data, i.e. why is `extStr = JSON.stringify(...)` and not just `extStr = { ... }`? I believe that is your problem.

**Comment by joeinnes** [comment]
Because I get a different error: Unhandled rejection Error: Invalid Request

This is the current code giving me the error above:

```
var data = {
              notes: task.notes ? task.notes + '\nDone...' : 'Done...',
              external: {
                'id': task.id,
                'data': "passedToIDT"
              }
            };
          
            client.tasks.update(task.id, data)
            .then(function (resp) {
                console.log(resp);
            });

```

**Comment by slobak** [comment]
Interesting. I wonder if the request is failing because the `task.id` already exists for another task in Asana? There is a uniqueness constraint there.

If you add a `.fail(...)` handler you may be able to get more detailed information. Whenever we return a 400 we generally include a message about the field that had a problem and what the problem was.

**Comment by slobak** [comment]
Another thought (from @praecipula) is that you may not have initialized your client with Oauth? External data is per-Oauth-app. But if you don't use Oauth, you cannot use the feature. Either way, the error message you're getting should be more revealing.

**Comment by joeinnes** [comment]
I was on Oauth, but should have thought about it more carefully and added the `.catch()` myself. Anyway, it told me that the ID needs to be a string. Coerced it, and now working beautifully. Thanks for all your help!
