### ISSUE TITLE
Typeahead method using SDK

### ISSUE THREAD

**Issue by tvvignesh** [Asana/node-asana#132]
Hi. May I know how to use the typeahead API: https://asana.com/developers/api-reference/typeaheads using the node.js SDK? 

I did not find it in the wiki and thus I am not sure how to use it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694763554707/279349353297362)

**Comment by periodic** [comment]
It's supported on the workspaces client.  You should be able to access it there:

https://github.com/Asana/node-asana/blob/master/lib/resources/gen/workspaces.js#L94

**Comment by tvvignesh** [comment]
@periodic: got it. thanks.
