### ISSUE TITLE
Chrome extension error

### ISSUE THREAD

**Issue by victor-cano** [Asana/node-asana#147]
Hi guys, I am following your example of login for a chrome extension, and it's giving me the below error, could you help me please. Thanks.

![image](https://user-images.githubusercontent.com/13294935/33507748-19edbc56-d6bc-11e7-98f3-a1fde7ebc7fc.png)

**Comment by theaeolianmachine** [comment]
Hi @victor-cano,

I'm not certain what example you're using - could you point me to a link of it? However, it looks like you're using [OAuth](https://asana.com/developers/documentation/getting-started/auth)?

If so, the error seems to point to the `redirect_uri` that you are passing in the application is not the `redirect_uri` that you've registered in the [Apps tab under your account settings in Asana](https://app.asana.com/-/account_api).

Could you verify that they're the same? If they are, would you mind sharing a code snippet?

**Comment by theaeolianmachine** [comment]
Hi @victor-cano; I'm going to close this out for now, but if you're still running into issues let us know and we'll reopen it.
