### ISSUE TITLE
readline error using create-react-app

### ISSUE THREAD

**Issue by JohannBoch22** [Asana/node-asana#168]
Hey, these are the commands I ran to start my new project
`mkdir Projects`
`cd Projects`
`npm create-react-app my_app`
`cd my_app`
`npm install asana --save `
`npm start`

I then tried to import the asana package into my app.js file:
`import * as Asana from 'asana'`

This is where an error was thrown on localhost:
> ./node_modules/asana/lib/auth/native_flow.js
> Module not found: Can't resolve 'readline' in '/Users/johannboch/Projects/my-app/node_modules/asana/lib/auth'

check out my repository: https://github.com/JohannBoch22/asana-error

pls help

Johann

**Comment by praecipula** [comment]
Hey, sorry I neglected to close this. The commit referenced above (https://github.com/Asana/node-asana/commit/55b6461e570758ef5fe089a82d9df1f3971ef56f) should have fixed the problem; feel free to ping/reopen if it didn't.
