### ISSUE TITLE
story changed events not emitted when listening on project events

### ISSUE THREAD

**Issue by iimez** [Asana/node-asana#172]
```
client.events.stream(projectId, {
	periodSeconds: 3,
	continueOnError: true,
}).on('data', ({ type, action, resource }) => {

	if (type == 'story' && resource.type == 'comment' && action == 'added') {
		// werks
	}

	if (type == 'story' && resource.type == 'comment' && action == 'changed') {
		// never happens :(
	}

	if (type == 'story' && resource.type == 'comment' && action == 'removed') {
		// werks
	}

})
```
No event is emitted when editing a comment in asana. I do receive events as expected on create/delete. Not sure if this is actually a problem with node-asana, but found no better place to post.

**Comment by iimez** [comment]
Hello @jjschnei, thanks for your response! :)

Just in case this issue gets further attention: My use case was trying to keep a database of all tasks including related conversation locally. For that I'd like to store the latest version of a comment, not the original one. Is there any other way to receive events on edited comments or do I need to poll for changes?

**Comment by jjschnei** [comment]
Thanks for sharing your use-case.  What's the underlying need that requires you to keep a local database of all tasks? 

Unfortunately, there is currently no way to get an event when a comment is edited.  While comments do have an `is_edited` field, it's not currently possible to determine when a comment was edited or if it has been edited more than once.  I've discussed this with the API team.  While there are some stability reasons for not sending more events on task edits, we would like to add more thorough task audit logs to the API.

**Comment by iimez** [comment]
That's great to hear! For now I'll just poll every few hours or so.

I've been using the API to sync the state of all Asana project tasks with a GitLab project's issues primarily because I was looking for a way to
- keep references of code changes to tasks
- complete tasks via git commit message

Basically my team loves Asana (rightfully so!) and I love keeping track which code needed to be changed to resolve a certain task so this is best of both worlds. I'm aware that there are integrations around for doing this but I can't bring these to sync data the way we need to (including custom fields and time tracking data by another Asana extension).

As to why I'd store the data: Seemed more robust to keep task state in an intermediate store instead of applying changes directly. I may skip persisting this data in the future but it felt like a good idea to keep a local database to link user IDs, further sync configuration and potentially run queries on the data.

Thank you all very much for your effort, Asana's UX is beautiful and so is it's API. :+1:
