### ISSUE TITLE
Can't use this library - This dependency was not found:  * fs

### ISSUE THREAD

**Issue by dugajean** [Asana/node-asana#177]
Whenever I try to build my Javascript with Webpack, it fails with this error:

```
This dependency was not found:

* fs in ./node_modules/readline/readline.js

To install it, you can run: npm install --save fs
```

I tried installing the required dependency with `yarn add fs --dev` and `npm install --save fs`. They practically the same so the error still persisted anyway.

The way I tried to import is with a standard `import Asana from 'asana'` and `const asana = require('asana')`. Neither worked.

I'm trying to use this library in the frontend/browser.

Help would be appreciated.

**Comment by rossgrambo** [comment]
Hey @dugajean !

Try the solution I posted here: https://forum.asana.com/t/node-library-requires-lib-unavailable-for-a-web-use/39891/4 . We're aware of this issue, but not prioritizing it, as the solution was getting muddy and theres currently a workaround.

Let me know if this doesn't fix it for you!
