### ISSUE TITLE
Asana deprecations

### ISSUE THREAD

**Issue by nairihar** [Asana/node-asana#182]
Hi, is this library issue?

<img width="957" alt="Screen Shot 2019-07-15 at 9 08 46 PM" src="https://user-images.githubusercontent.com/15065065/61234694-d08c9680-a744-11e9-9650-672949cb4c7b.png">

**Comment by rossgrambo** [comment]
Hi @nairihar, 

I just updated our readme to explain how to work with [these warnings](https://github.com/Asana/node-asana/blob/master/README.md#options).

When you made a request to the Asana API and an upcoming deprecation affects the call, the API returns a Asana-Change header.

We decided to start surfacing these headers in our client libraries as warnings. So you will see one for each request until you either opt_in to the deprecation or disable these warnings.

If you add these options to your client:

    asana.Client.create({"defaultHeaders", {"asana-enable": "new-sections,string_ids"}});

You will be using the new functionality. You can read more about each of them by following the links in the warnings.

If you do nothing, then the deprecation will take effect on the date listed in our [deprecation docs](https://asana.com/developers/documentation/getting-started/deprecations#active-deprecations), and your requests may start to fail.

**Comment by nairihar** [comment]
thanks, @rossgrambo for the info.

I've already set those headers. but when I'm trying to load projects it returns "new_sections" deprecation log.

```js
client.projects.findAll({
    workspace : workspace.gid,
    opt_fields: 'id,name,layout',
    archived  : false,
    limit     : 100,
})
```

Could you help to understand the issue for this case?

Because I think the library itself should fix the version related issues(I mean do the call to the other endpoint...).

**Comment by nairihar** [comment]
Hi @rossgrambo thanks for the update, is there any other way to get the layouts for the projects?

**Comment by nairihar** [comment]
@rossgrambo thanks for the info

**Comment by davidworkman9** [comment]
There's a syntax error in the code example. For anyone that runs into this it should be:
```
asana.Client.create({"defaultHeaders": {"asana-enable": "new-sections,string_ids"}});
```
