### ISSUE TITLE
If I add type definition and migrate to TypeScript, would you review and merge?

### ISSUE THREAD

**Issue by euxn23** [Asana/node-asana#188]
Now DefinitlyTyped provides `@types/asana`, but this library lack some response values...
So, I'd like to add type definitions to `node-asana` repository, how do you think?

**Comment by rossgrambo** [comment]
Sure! If you're suggesting adding type definitions, then yes, I'd review and merge. 

If you're suggesting we migrate the whole library to typescript, I'd be more skeptical, as it would be a big change. 😄 

If you find that you need to make changes to the files in the gen/ folder, let me know, as those are generated from `asana-api-meta`, and the changes will need to be in that repo, and not this one.
