### ISSUE TITLE
Tasks findByProject(projectId, params), can't get any params to work

### ISSUE THREAD

**Issue by lastpixelstudios** [Asana/node-asana#190]
Hello, I am trying to find all tasks on a project (which I can do), but it is only returning gid, name & resource_type. I wanted to know how the params work. I tried to add ['due_on'], which is what I need, but that doesn't seem to work. Do I have to make a separate call directly to the task?

I know when looking at the Asana API docs and testing the Tasks Explorer, you can add opt_fields to return additional fields. What is the best way to retrieve additional fields for tasks when pulling all tasks on a project?

Thx in advance.

**Comment by rossgrambo** [comment]
You should be able to ask for the fields you want like this:

```
    client.tasks.findByProject( project.gid, {
        fields: "due_on"
    }).then(function (tasks) {
        console.log(tasks.data);
    });
```

**Comment by lastpixelstudios** [comment]
Brilliant! Thank you @rossgrambo it worked! My issue was not including "fields" within the params. I appreciate the solve and quick turnaround.
