### ISSUE TITLE
Unsupported response type "token"

### ISSUE THREAD

**Issue by atom-goliver** [Asana/node-asana#192]
Trying to use the library (in a browser) with the oAuth method, I get the following error after my application sends the user to the Asana site to authorize the app...

### Error
```unsupported_response_type: The `token` response type is deprecated.```

If I change the "response_type" from "token" to "code" in the URL, the user can authorize the app and is redirected back correctly (even though I can't figure out how to actually _finish_ the authorization process once a user lands back on the app). I see there have been issues in the past (#144 and #120), but nothing I seem to do is allowing the login to work. Additionally, the link in those issues to the [implicit grant flow](https://asana.com/developers/documentation/getting-started/auth#implicit-grant) gets redirected to the "authentication basics" section of the developer docs, and a search for "implicit grant" in the documentation doesn't return any results.

**Comment by rossgrambo** [comment]
Sadly, that response is correct. The oauth spec deprecated the `token` oauth flow (implicit grant), so we went ahead and deprecated it. 

You'll have to setup a server to use the `code` flow. I'd recommend using a small Google Cloud Function or AWS Lambda, as they are easy & free (for a generous amount of traffic).

I'm pushing to allow client side authorization code flow (no server needed), but we haven't made that available yet, as it requires quite a bit of security review and API updates.

**Comment by allthingsclowd** [comment]
> Sadly, that response is correct. The oauth spec deprecated the `token` oauth flow (implicit grant), so we went ahead and deprecated it.
> 
> You'll have to setup a server to use the `code` flow. I'd recommend using a small Google Cloud Function or AWS Lambda, as they are easy & free (for a generous amount of traffic).
> 
> I'm pushing to allow client side authorization code flow (no server needed), but we haven't made that available yet, as it requires quite a bit of security review and API updates.

Hi Ross,

Any chance of providing an example blog of how these `easy proxy services` can be setup to achieve the suggested work-around?

Many thanks,
Graham

**Comment by rossgrambo** [comment]
Hey @allthingsclowd ,

Here's a walkthrough I created that uses Google Cloud Functions and implements an extra secure layer called pkce. https://github.com/Asana/devrel-examples/tree/master/javascript/pkce_oauth

You're the first person I'm sharing it with, so I'm sure there are issues/things I missed. Don't hesitate to ping me and/or create an issue in that repo for any problems you have!

Hope this helps!

Best,
Ross
