### ISSUE TITLE
Create task not working

### ISSUE THREAD

**Issue by julioverissimo88** [Asana/node-asana#194]
Hi 
I am trying to create task from API 

let newTask = { name: "Minha Task", completed: true };

`
client.tasks.createInWorkspace(workspace_id, newTask).then((response) => {
    tasks = response.data;
    console.log(response);
}).catch(function (ex) {
    console.log(ex.message);
});
`

But, Not working for me. the code has no error but does not insert the task

**Comment by rossgrambo** [comment]
I never saw this issue come by my inbox, so I apologize for not answering sooner.

If you upgrade to our latest version 0.18.3, you can set this:

```js
client.dispatcher.debug(true);
```

Which should show you exactly what you're sending to Asana's API and exactly what the API is sending back. 

Assuming asana's api is getting your request correctly, you should look into the response body for the gid. Then check if Asana has it by hitting /tasks/{gid} or .getTasks(gid)

Going to close this for now, but I'll reopen if you still have issues!
