### ISSUE TITLE
[Question] Batch API

### ISSUE THREAD

**Issue by oltreseba** [Asana/node-asana#202]
Is it possible to use the batch API with this page? If yes, how?

It looks like there is some code for that, but it's not actually in use.

**Comment by rossgrambo** [comment]
You're totally right. I added it into our tooling, but didn't manually add the "resource" of batchAPI.

Upgrade to 0.18.4 and you can use batch like this:

```js
// Body from https://developers.asana.com/docs/#submit-parallel-requests
body = {
    "actions": [
        {
            "relative_path": "/users/me",
            "method": "get"
        }
    ]
};
client.batchAPI.createBatchRequest(body)
    .then(function(data) {
        console.log(data[0]);
    });
```
