### ISSUE TITLE
Storing new access tokens

### ISSUE THREAD

**Issue by jhoch** [Asana/node-asana#205]
I am in my first day or two of using `node-asana`.  First off, thanks for releasing and maintaining this SDK.

The way that I am invoking the Asana client, I am fetching a refresh and access token out of my database, per user request.  This client correctly handles expired access tokens, which is great, because my requests succeed.  However, the new access token is never stored in my DB, and so if I am making N requests per hour, I am using my refresh token to gain access to a new access token N times per hour instead of once per hour.

Is there a way to listen for new access tokens so I can store them on my end?

Here is the analogous part of the OAuth2 documentation for Google NodeJS SDK: [Handling refresh tokens](https://github.com/googleapis/google-api-nodejs-client/tree/62f819397567d9e584cb18e5e48a0ff615b542a1#handling-refresh-tokens)

**Comment by jhoch** [comment]
I just saw this pull request with the same idea: https://github.com/Asana/node-asana/pull/139/files.  The PR is 3 years stale but the diff is very small.  I would be happy if it were released.

Let me know if help from my end would speed this along (or get in the way!), and thanks again!

**Comment by rossgrambo** [comment]
Thanks for pointing out this use case and showing me the PR. I tested the PR and it lgtm, so I went ahead and merged it. I'll do a new version deploy on ~friday and this will be included.
