### ISSUE TITLE
Incorrect type definition for Tasks.CreateParams

### ISSUE THREAD

**Issue by NielsKersic** [Asana/node-asana#207]
The TypeScript definition for `Tasks.CreateParams` is incorrect. The definition looks like this now: 

```TypeScript
interface CreateParams {
     name: string;
    completed?: boolean;
    hearted?: boolean;
    notes?: string;
    custom_fields?: Object;
}
```

This means that `name` is a required field, which is not actually the case. Also updating other top level properties of tasks, like `due_on` will result in an "Argument of type x not assignable to parameter of type 'CreateParams'"

I wouldn't mind creating a PR, but I am unsure which properties of tasks you're actually able to update.

**Comment by rossgrambo** [comment]
Hey @NielsKersic ,

I was unaware that we offered types for this. Could you point me to the file where these are defined?

**Comment by NielsKersic** [comment]
@rossgrambo These are actually in the [@types/asana package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/asana/index.d.ts), but seeing as that is created and maintained by a third party, I should have posted my issue there. Apologies!

**Comment by rossgrambo** [comment]
Oh! We should either take over that library or offer types within this one. It would be fairly low hanging fruit for us as we are generating all of this from a static typed context anyway. I'll make a task for us to look into it. Thanks!
