### ISSUE TITLE
node-asana not working with react native

### ISSUE THREAD

**Issue by meliodev** [Asana/node-asana#213]
Hello, I tried node-asana within a react native project but it didn't work.

**Comment by rossgrambo** [comment]
Hello @meliodev,

What is the error that you're getting?

**Comment by rossgrambo** [comment]
Hey @meliodev ,

I went ahead and tested anyway. Everything works as expected for me. I did:

1. `npm install -g expo-cli`
2. `expo init AwesomeProject`
3. `cd AwesomeProject`
4. `npm install asana`
5. Change app.js to:
```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Asana from 'asana';

export default function App() {
  fetch('https://app.asana.com/api/1.0/tasks/1234567890', {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      'Authorization': 'Bearer ' + '0/1234567890212345678990'
    }
  }).then((json) => {
    console.log(json);
  });

  const client = Asana.Client.create().useAccessToken('0/1234567890212345678990');
  client.tasks.getTask('1234567890').then(function(task) {
    console.log(task);
  });

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
6. `npm start`
7. See console logs. 

Both a raw request to the API works, and the node-asana library worked for me. Let me know if you're experiencing something different!

**Comment by rossgrambo** [comment]
I'm going to close this, but I'm happy to reopen if we need to!

**Comment by meliodev** [comment]
Thank you for your reply ! Your answer helped. Now it works.
