### ISSUE TITLE
Request Timeout is not propagated to the Dispatcher

### ISSUE THREAD

**Issue by rv-vmartyniuk** [Asana/node-asana#219]
The problem is in the Client `create` method where the `requestTimeout` is mapped to the `timeout` property. However, Dispatcher refers to the `requestTimeout` instead of `timeout`.

```js
return new Client(
      new Dispatcher({
        asanaBaseUrl: options.asanaBaseUrl,
        timeout: options.requestTimeout,
        defaultHeaders: options.defaultHeaders,
        defaultProxy: options.defaultProxy,
        logAsanaChangeWarnings: options.logAsanaChangeWarnings
      }),
      options);
```

**Comment by rossgrambo** [comment]
Thank you @rv-vmartyniuk !

You're absolutely right. I'll include this fix in the next deploy.

**Comment by rv-vmartyniuk** [comment]
@rossgrambo thank you for the update. Also, I've just noticed that the `retryOnRateLimit` property is not propagated down to dispatcher either. This is very critical part for our enterprise as we perform a several hundreds complex searches in one batch process and obviously we hit rate limit of 60 requests/minute.

Can you please let us know also the estimated date for the next deploy so we can do some planning on our end?

**Comment by rossgrambo** [comment]
For the retryOnRateLimit, this should happen automatically within rate_limit_enforced.js as the API returns a retry-after header. Are you saying that functionality is broken?
