### ISSUE TITLE
Can't update task

### ISSUE THREAD

**Issue by eboody** [Asana/node-asana#222]
Hey!

Taking a super simple example, Let's say I'm just trying to change the assignee. I made sure the user GID is correct and this indeed returns the task but nothing actually changed.

```
    await client.tasks.updateTask(task.gid, {
        "data": {
            "assignee": "1188772692995363",
        }
    });
```

**Comment by rossgrambo** [comment]
Hello @eboody !

If you're using our client library, you don't need to include the "data" wrapper. Meaning your code should look like:

```
await client.tasks.updateTask(task.gid, {
        "assignee": "1188772692995363"
    });
```

Hope this helps :)

**Comment by eboody** [comment]
Thanks @rossgrambo !!
