### ISSUE TITLE
Bug: Task Templates API not reflecting any updates after creation

### ISSUE THREAD

**Issue by 0xc00010ff** [Asana/node-asana#295]
If you turn a task into a task template, then change anything about the template (including deleting it), it will not reflect in the [templates API](https://developers.asana.com/reference/gettasktemplate).

To reproduce: Make a task template, change something about it, see that the API doesn't reflect those changes
1. In a test Asana account, create a Task called "Example - as a Task"
2. Then turn the task into a template through the UI
3. Update the title of the template to "Example - as a Template"
4. Query the [API](https://developers.asana.com/reference/gettasktemplate) and see that the task is still named "Example - as a Task"
5. Delete the task in the UI and see that the task is still accessible and named "Example - as a Task"
6. Query the [list of templates by project id](https://developers.asana.com/reference/gettasktemplates) and see that the deleted task is included in the list. 

The behavior is the same across both projects I tested, both in the API playground linked above and in the Node package. 

Seems like the API and the UI are not referencing the same records. We have this running in prod and it's causing funky behavior. Wonder if I should just stop using templates and use specially marked tasks instead. Any insight or suggestions appreciated.

**Comment by jv-asana** [comment]
Hi @0xc00010ff,

I think there might be confusion as to how you update task templates in Asana.

What you actually did in your steps is you edited the name of a closed task. When you convert a task to a task template in Asana, that task is closed and if you change the name of that closed task it will change the name of that task that was closed not the task template. So if you do a [Get a task](https://developers.asana.com/reference/gettask) API call you should see the name of that closed task be updated to `Example - as a Template` if you decide to click on the **"Reopen task"** button on that closed task, it will be converted back to a regular task with the updated title of `Example - as a Template`

<img width="1510" alt="closed_task" src="https://github.com/Asana/node-asana/assets/99784540/dd99c7a9-508c-4fa5-8675-81086c643bc8">

Here's how you would update a task template in Asana:

1. In an Asana project (`PROJECT_A`) create a task called `Example - as a Task`
2. On the `Example - as a Task` task click on the **"..."** icon on the top right > **"Convert task to template"**
3. In `PROJECT_A` click on the **"Customize"** button > **"task templates"** > select the task template **"Example - as a Task"**
4. Update the title from `Example - as a Task` to `Example - as a Template` > click on the **"Done"** button
5. Make an API call to [Get multiple task template](https://developers.asana.com/reference/gettasktemplates) endpoint and provide it with the `project` of `PROJECT_A` in the query params > you should see the task template you just created and the name being `Example - as a Template`

<img width="1507" alt="edit_task_template" src="https://github.com/Asana/node-asana/assets/99784540/7ccadaf0-181b-4db8-a005-45b4dc1c46f5">
