### ISSUE TITLE
Add file upload for attachments

### ISSUE THREAD

**Issue by pspeter3** [Asana/node-asana#4]

**Comment by jpike88** [comment]
I'm guessing this isn't happening any time soon.

**Comment by davinci0428** [comment]
I need this. When will it happen?

**Comment by PaulMougel** [comment]
FYI,  [this link](https://forum.asana.com/t/cant-figure-out-how-to-upload-attachments-using-node-asana/73017/11) mentions a way to do it by using the raw dispatcher object:
```
var params = {
    method: 'POST',
    url: "https://app.asana.com/api/1.0/tasks/1234567890/attachments",
    formData: {
        file: fs.createReadStream('test.png')
    },
    headers: {
        "Content-Type": "multipart/form-data"
    },
};
client.dispatcher.dispatch(params, {});
```

Hope that's helpful!

**Comment by rossgrambo** [comment]
Thank you @PaulMougel !
