### ISSUE TITLE
Basic authentication not working in browserified version

### ISSUE THREAD

**Issue by marcboscher** [Asana/node-asana#41]
Using the basicAuth client on the browserified lib (dist/asana.js) always sends an invalid authorization header.

This is caused by this bug: https://github.com/iriscouch/browser-request/issues/41

A workaround patch could be: 

```javascript
Client.basicAuth = function(apiKey) {
  return new Client(new Dispatcher('auth', {
    user: apiKey,
    pass: '',
    // Workaround for browser-request issue #41
    username: apiKey,
    password: ''
  }));
};
```

**Comment by marcboscher** [comment]
It doesn't seem like the `auth.bearer` option is even support by the browser-request lib, so the oauth client will probably fail too (though I haven't tried it).

Maybe the superagent lib is a better option than request since it supports the browser out of the box.

**Comment by slobak** [comment]
Thanks for raising the issue with browser-request; your workaround looks
reasonable, we'll look into this.

**Comment by pspeter3** [comment]
I think `superagent` may be the way to go since we want to support both the server and the browser.

**Comment by marcboscher** [comment]
Been using superagent myself to interact with Asana. Working great, for example:

``` Javascript
function getTasks (project) {
  return request
    .get(apiUrl + "tasks")
    .query({"project": project.id})
    .query({"opt_fields": "id,name,notes,modified_at,completed,assignee.name,assignee.email,tags.name,projects.name"})
    .auth(helper.getUser(), helper.getPsw())
    .promise()
    .then(function (res) {
      return res.body.data.filter(function (task) {
        return task.name.trim().length > 0;
      });
    });
}
```


Using this to wrap superagent requests into bluebird promises (adds the promise() method):
https://www.npmjs.com/package/superagent-bluebird-promise
https://github.com/KyleAMathews/superagent-bluebird-promise/blob/master/index.js

**Comment by pspeter3** [comment]
I added a pull request https://github.com/iriscouch/browser-request/pull/42

**Comment by slobak** [comment]
I believe we addressed this workaround a while ago, I just re-verified this is no longer an issue.
