### ISSUE TITLE
State not passed through when using PopupFlow

### ISSUE THREAD

**Issue by keenanpayne** [Asana/node-asana#68]
The url being used to initiate the popup flow does not contain the state parameter, so the authorization process doesn't complete correctly.

(PopupFlow.prototype.startAuthorization)

**Comment by keenanpayne** [comment]
@raysaagar

**Comment by epelz** [comment]
I think I hit this bug too, and #64 fixed it. Give that a try? We should also merge that in.

**Comment by keenanpayne** [comment]
Let me try that and see if it fixes it. Thanks!

**Comment by keenanpayne** [comment]
Unfortunately that did not fix the issue on my end
