### ISSUE TITLE
support for pagination

### ISSUE THREAD

**Issue by dsernst** [Asana/node-asana#71]
Does this library support pagination? It looks like the request can be manually retried by passing the offset string as a param, but would it be possible to have the library do this automatically?

**Comment by slobak** [comment]
Yes, it does support pagination. What do you mean by "automatically"?

Look at `Client.nextPage` or `Client.stream`, both of these methods interface with our request paging mechanism.

**Comment by dsernst** [comment]
I needed to get all of the tasks for a project, where the number of tasks could be up to 300. I ended up writing this helper function to recursively traverse the linked list of pages and return all tasks as an array  (with very helpful assistance from @danthareja):

```javascript
function getAllTasksByProjectId(id, debug) {
  return new Promise(function (resolve, reject) {
    var all = [];
    (function getAPageOfTasks(offset) {
      asana.tasks.findByProject(id, {offset: offset})
        .then(function (data) {
          if (debug) {
            console.log(data);
          }
          return data;
        })
        .then(function (tasks) {
          [].push.apply(all, tasks.data);
          if (tasks.next_page) {
            getAPageOfTasks(tasks.next_page.offset);
          } else {
            resolve(all);
          }
        })
        .catch(reject);
    }());
  });
}
```

It would be nice if this library could handle this sort of querying automatically. Maybe I missed `Client.stream` , would this be an easier way to get all the results?

**Comment by slobak** [comment]
`Client.stream` will give you a stream-based interface to the events, i.e. you'll get `data` and `end` callbacks which you can use to populate an array if that's what you need (though it's best when used to pipe to another stream).

The main source of our reluctance to provide your request from the start is that we don't want developers to just mindlessly slurp up all data and ignore pagination—this had bad consequences for performance as the underlying data set grows, so if you're going to run an operation that potentially consumes thousands of tasks, your code should be mindful of that.

We'll consider adding some kind of `all` method to either `Client` or `paging`, though, with the appropriate caution—seeing as many developers will probably just attempt to write it themselves. :)

**Comment by slobak** [comment]
https://github.com/Asana/node-asana/commit/01114be321635ec04cbd301d8ef7cfed8a921b04
