### ISSUE TITLE
How to set/retreive custom external ID?

### ISSUE THREAD

**Issue by ambikads** [Asana/node-asana#87]
Can't find any working example and the documentation in Asana API is not very helpful.

I tried adding the external ID and created the task (with other params not shown here) like below

````params['external'] = [ {id: '12345'}]````
````Asana.tasks.create(params).then (response) ->````

This did not show any errors. However, when I tried to retrieve this, I get a invalid request

````Asana.tasks.findByExternalId("12345").then  (response) ->
         ..... ````

**Comment by ambikads** [comment]
Can someone please help? Any working example? Thanks in advance

**Comment by agnoster** [comment]
Did you try `params.external = { id: '12345' }`? The custom fields should not be wrapped in an extra array, I think.

**Comment by ambikads** [comment]
@agnoster That gives me a "invalid request" while creating the task.

    
    { [Error: Invalid Request]
      message: 'Invalid Request',
      stack: 'Error: Invalid Request\n  at InvalidRequest.AsanaError     (/bot/node_modules/asana/lib/errors/error.js:4:11)\n  at new InvalidRequest (/bot/node_modules/asana/lib/errors/invalid_request.js:5:14)\n  at Request._callback (/bot/node_modules/asana/lib/dispatcher.js:140:23)\n  at Request.self.callback (/bot/node_modules/asana/node_modules/request/request.js:197:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/bot/node_modules/asana/node_modules/request/request.js:1050:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/bot/node_modules/asana/node_modules/request/request.js:996:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickCallback (node.js:448:13)\n',
      status: 400,
      value: { errors: [ [Object] ] } }

**Comment by agnoster** [comment]
Can you include the actual errors text? You're console.logging the whole response and the errors value is only being shown as [Object] - if you `console.log(response.value.errors)` it should show up.

**Comment by ambikads** [comment]
@agnoster ahh this is the message I see

````[ { message: 'external: Accessing external data requires authenticating with OAuth' } ]````

**Comment by ambikads** [comment]
I use basisAuth, I will try with OAuth and update here. Thanks for your help.

**Comment by agnoster** [comment]
Ah yes - I believe that's covered in the documentation, but external data (since it is only visible to the OAuth app that creates it) can only be created when using OAuth.
